version: '3'

services:
  db:
    container_name: 'smart-medicine-cup-backend-database'
    image: postgres
    env_file:
      - ./.env.secret
    tty: True

  web:
    container_name: 'smart-medicine-cup-backend-web'
    build: .
    env_file:
      - ./.env.secret
    volumes:
      - .:/home/smart-medicine-cup-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migrate
      - db
    tty: True

  migrate:
    container_name: 'smart-medicine-cup-backend-migrate'
    build: .
    env_file:
      - ./.env.secret
    volumes:
      - .:/home/smart-medicine-cup-backend
    command: python manage.py migrate
    depends_on:
      - migrations
      - db
    tty: True

  migrations:
    container_name: 'smart-medicine-cup-backend-migrations'
    build: .
    env_file:
      - ./.env.secret
    volumes:
      - .:/home/smart-medicine-cup-backend
    command: python manage.py makemigrations
    depends_on:
      - db
    tty: True

  command:
    container_name: 'smart-medicine-cup-backend-command'
    build: .
    volumes:
      - .:/home/smart-medicine-cup-backend
    tty: True
